#!/bin/sh -eu
#
# Picks random line from 4 files and combine them. The output should
# be funny in some degree. The first argument is a file to write word
# log to.

log="$1"

pick () {
    shuf -n 1 "$1"
}

while true; do
    line="`pick ihmiset.txt` `pick tyylit.txt`: `pick asiat.txt` `pick fiilikset.txt`"
    echo `date --rfc-3339=seconds` "$line" >>$1
    echo "$line"
    sleep 1m
done
