#!/bin/sh -eu

if test $# -eq 0; then
    exec >&2
    echo "Usage: $0 PREV_ID"
    echo
    echo "PREV_ID is the previous block id url which has been sent already."
    echo "It is different from block height! In 2014-08-19 it was /blocks/133739"
    exit 1
fi

PREV_ID=$1
RAW_HTML=`mktemp`

clean () {
    echo
    echo "Last block was $PREV_ID"
    rm "$RAW_HTML"
    exit
}

trap clean EXIT INT

while true; do
    echo -n .

    curl -sfm 30 -o "$RAW_HTML" "http://80.240.143.139/"
    NEXT_ID=`xsltproc --novalid --html --stringparam last_block_url "$PREV_ID" find_new.xsl "$RAW_HTML" 2>/dev/null`

    # Start over if we got nothing
    if test "$NEXT_ID" = ""; then
    	sleep 10
    	continue
    else
	echo " found $NEXT_ID"
    	PREV_ID="$NEXT_ID"
    fi

    curl -sfm 30 -o "$RAW_HTML" "http://80.240.143.139/$NEXT_ID"
    xsltproc --novalid --html fimk-blockexplorer-simplify.xsl "$RAW_HTML" 2>/dev/null
done
